# Generated by Django 4.2.4 on 2023-08-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('cafe', 'cafe'), ('lounge', 'lounge'), ('Food', 'Food'), ('New Experince', 'New Experince')], max_length=20)),
                ('publish_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_photos/')),
            ],
        ),
    ]
